name: 'Project 02'

on:
  workflow_dispatch:
  push:
    paths:
      - projects/02/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: project02
        run: find projects/02 -name *.tst | xargs -t -L1 ./tools/HardwareSimulator.sh

