name: 'Project 04'

on:
  workflow_dispatch:
  push:
    paths:
      - projects/04/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: project04-mult
        run: ./tools/CPUEmulator.sh ./projects/04/mult/Mult.tst
      - name: project04-fill
        run: ./tools/CPUEmulator.sh ./projects/04/fill/FillAutomatic.tst
